#!/usr/bin/env bash
# Interactive wizard (or copy vm-host.env.example to vm-host.env and edit by hand).
# Also invoked from setup-host.sh after host checks (optional).
set -euo pipefail

_HS_HOST_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/sandbox-root.sh
source "$_HS_HOST_DIR/lib/sandbox-root.sh"
# shellcheck source=lib/vm-host-env.sh
source "$_HS_HOST_DIR/lib/vm-host-env.sh"

BASE="$(sandbox_repo_root)"
EXAMPLE="$BASE/host/vm-host.env.example"
OUT="$BASE/host/vm-host.env"
PW_ENV="$BASE/secrets/vm-password.env"

SKIP_PASSWORD=false
for arg in "$@"; do
  case "$arg" in
    --skip-password) SKIP_PASSWORD=true ;;
    -h | --help)
      cat <<EOF
Usage: $(basename "$0") [--skip-password]

  Interactive prompts for host/vm-host.env (disk, RAM, vCPUs, …) and, by default,
  secrets/vm-password.env: auto-generated password, or type your own if you decline auto-generation.

  Run from ./setup-host.sh (optional) or any time before host/create-vm-*.

  --skip-password   Do not create or change secrets/vm-password.env
EOF
      exit 0
      ;;
    *)
      echo "Unknown option: $arg" >&2
      exit 1
      ;;
  esac
done

if [[ ! -f "$EXAMPLE" ]]; then
  echo "Missing $EXAMPLE" >&2
  exit 1
fi

if [[ "$SKIP_PASSWORD" != true ]]; then
  echo ""
  echo "=== Guest password (kickstart user 'ai') ==="
  read -r -p "Create secrets/vm-password.env with an auto-generated password? [Y/n] " pw_ans || true
  case "${pw_ans:-y}" in
    y | Y | yes | "")
      if [[ -f "$PW_ENV" ]] && grep -qE '^[[:space:]]*VM_PASSWORD[[:space:]]*=' "$PW_ENV"; then
        read -r -p "File exists. Keep [Y] or regenerate [r]? " pw_reg || true
        case "${pw_reg:-y}" in
          r | R) "$_HS_HOST_DIR/write-vm-password-env.sh" --force ;;
          *) echo "Keeping existing $PW_ENV" ;;
        esac
      else
        "$_HS_HOST_DIR/write-vm-password-env.sh"
      fi
      ;;
    *)
      echo "You will be prompted to type and confirm the password."
      "$_HS_HOST_DIR/write-vm-password-env.sh" --manual
      ;;
  esac
fi

set -a
# shellcheck disable=SC1090
source "$EXAMPLE"
set +a
vm_host_apply_defaults_linux
vm_host_apply_defaults_mac

ask() {
  local label="$1"
  local default="$2"
  local reply
  read -r -p "$label [$default] " reply || true
  if [[ -z "${reply// }" ]]; then
    REPLY="$default"
  else
    REPLY="$reply"
  fi
}

echo ""
echo "=== VM sizing and paths ==="
echo "→ $OUT"
echo "(Press Enter to keep the value in brackets.)"
echo ""

ask "VM name" "$VM_NAME"
VM_NAME="$REPLY"

ask "Disk size (GiB)" "$VM_DISK_GB"
VM_DISK_GB="$REPLY"

ask "RAM (MiB; 1024 MiB ≈ 1 GiB)" "$VM_MEMORY_MIB"
VM_MEMORY_MIB="$REPLY"

ask "vCPU count" "$VM_VCPUS"
VM_VCPUS="$REPLY"

ask "CPU mode (Linux virt-install --cpu)" "$VM_CPU_MODE"
VM_CPU_MODE="$REPLY"

ask "Fedora release" "$FEDORA_VER"
FEDORA_VER="$REPLY"

ask "Libvirt image directory (Linux)" "$VM_DIR"
VM_DIR="$REPLY"

ask "Libvirt NAT network name (Linux)" "$VM_LIBVIRT_NETWORK"
VM_LIBVIRT_NETWORK="$REPLY"

ask "Workstation live ISO URL (Mac / Windows)" "$VM_ISO_URL"
VM_ISO_URL="$REPLY"

ask "Hyper-V virtual switch name (Windows)" "${VM_HYPERV_SWITCH:-Default Switch}"
VM_HYPERV_SWITCH="$REPLY"

read -r -p "Optional netinstall URL for Linux (virt-install --location; Enter = default mirror): " LOC_EXTRA || true
LOC_EXTRA="${LOC_EXTRA// }"

{
  echo "# Generated by host/configure-vm-host.sh — edit by hand or re-run this wizard."
  printf 'VM_NAME=%q\n' "$VM_NAME"
  printf 'VM_DISK_GB=%q\n' "$VM_DISK_GB"
  printf 'VM_MEMORY_MIB=%q\n' "$VM_MEMORY_MIB"
  printf 'VM_VCPUS=%q\n' "$VM_VCPUS"
  printf 'VM_CPU_MODE=%q\n' "$VM_CPU_MODE"
  printf 'FEDORA_VER=%q\n' "$FEDORA_VER"
  printf 'VM_DIR=%q\n' "$VM_DIR"
  printf 'VM_LIBVIRT_NETWORK=%q\n' "$VM_LIBVIRT_NETWORK"
  printf 'VM_ISO_URL=%q\n' "$VM_ISO_URL"
  printf 'VM_HYPERV_SWITCH=%q\n' "$VM_HYPERV_SWITCH"
  if [[ -n "$LOC_EXTRA" ]]; then
    printf 'LOCATION_URL=%q\n' "$LOC_EXTRA"
  fi
} > "$OUT"

echo ""
echo "Wrote $OUT"
echo "Next: run host/create-vm-*.sh for your OS."
