#Requires -Version 5.1
# Interactive wizard for host\vm-host.env + secrets\vm-password.env (same idea as configure-vm-host.sh).
param(
    [switch]$SkipPassword,
    [switch]$Help
)

$ErrorActionPreference = "Stop"

if ($Help) {
    Write-Host @"
Usage: .\host\configure-vm-host.ps1 [-SkipPassword]

  Prompts for VM sizing and writes host\vm-host.env.
  By default also creates secrets\vm-password.env (random password, or type your own if you decline).

  Use from setup-host.ps1 or before host\create-vm-windows.ps1.
"@
    exit 0
}

$HostDir = $PSScriptRoot
. "$HostDir\lib\read-vm-host-env.ps1"
$Base = Get-SandboxRepoRoot -HostScriptDirectory $HostDir
$VmEnv = Get-VmHostEnvMerged -RepoRoot $Base
$Out = Join-Path $Base "host\vm-host.env"
$Example = Join-Path $Base "host\vm-host.env.example"

if (-not (Test-Path -LiteralPath $Example)) {
    Write-Error "Missing $Example"
}

function Escape-BashSingleQuoted([string]$s) {
    if ($null -eq $s) { return "" }
    return $s -replace "'", "'\''"
}

if (-not $SkipPassword) {
    Write-Host ""
    Write-Host "=== Guest password (kickstart user 'ai') ==="
    $pwAns = Read-Host "Create secrets\vm-password.env with an auto-generated password? [Y/n]"
    if ($pwAns -eq '' -or $pwAns -match '^[Yy]') {
        $pwFile = Join-Path $Base "secrets\vm-password.env"
        if ((Test-Path -LiteralPath $pwFile) -and ((Get-Content -Raw -LiteralPath $pwFile) -match '(?m)^\s*VM_PASSWORD\s*=')) {
            $reg = Read-Host "File exists. Keep [Y] or regenerate [r]?"
            if ($reg -match '^[Rr]') {
                & "$HostDir\write-vm-password-env.ps1" -Force
            }
            else {
                Write-Host "Keeping existing $pwFile"
            }
        }
        else {
            & "$HostDir\write-vm-password-env.ps1"
        }
    }
    else {
        Write-Host "You will be prompted to type and confirm the password."
        & "$HostDir\write-vm-password-env.ps1" -Manual
    }
}

Write-Host ""
Write-Host "=== VM sizing and paths ==="
Write-Host "-> $Out"
Write-Host ""

function Ask([string]$label, [string]$default) {
    $r = Read-Host "$label [$default]"
    if ([string]::IsNullOrWhiteSpace($r)) { return $default }
    return $r
}

$VM_NAME = Ask "VM name" $VmEnv['VM_NAME']
$VM_DISK_GB = Ask "Disk size (GiB)" $VmEnv['VM_DISK_GB']
$VM_MEMORY_MIB = Ask "RAM (MiB)" $VmEnv['VM_MEMORY_MIB']
$VM_VCPUS = Ask "vCPU count" $VmEnv['VM_VCPUS']
$VM_CPU_MODE = Ask "CPU mode (Linux virt-install --cpu)" $VmEnv['VM_CPU_MODE']
$FEDORA_VER = Ask "Fedora release" $VmEnv['FEDORA_VER']
$VM_DIR = Ask "Libvirt image directory (Linux)" $VmEnv['VM_DIR']
$VM_LIBVIRT_NETWORK = Ask "Libvirt NAT network name (Linux)" $VmEnv['VM_LIBVIRT_NETWORK']
$VM_ISO_URL = Ask "Workstation live ISO URL (Mac / Windows)" $VmEnv['VM_ISO_URL']
$VM_HYPERV_SWITCH = Ask "Hyper-V virtual switch name (Windows)" $VmEnv['VM_HYPERV_SWITCH']
$locExtra = Read-Host "Optional netinstall URL for Linux (Enter for default mirror)"

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("# Generated by host/configure-vm-host.ps1, edit by hand or re-run the wizard.")
[void]$sb.AppendLine(("VM_NAME='{0}'" -f (Escape-BashSingleQuoted $VM_NAME)))
[void]$sb.AppendLine(("VM_DISK_GB='{0}'" -f (Escape-BashSingleQuoted $VM_DISK_GB)))
[void]$sb.AppendLine(("VM_MEMORY_MIB='{0}'" -f (Escape-BashSingleQuoted $VM_MEMORY_MIB)))
[void]$sb.AppendLine(("VM_VCPUS='{0}'" -f (Escape-BashSingleQuoted $VM_VCPUS)))
[void]$sb.AppendLine(("VM_CPU_MODE='{0}'" -f (Escape-BashSingleQuoted $VM_CPU_MODE)))
[void]$sb.AppendLine(("FEDORA_VER='{0}'" -f (Escape-BashSingleQuoted $FEDORA_VER)))
[void]$sb.AppendLine(("VM_DIR='{0}'" -f (Escape-BashSingleQuoted $VM_DIR)))
[void]$sb.AppendLine(("VM_LIBVIRT_NETWORK='{0}'" -f (Escape-BashSingleQuoted $VM_LIBVIRT_NETWORK)))
[void]$sb.AppendLine(("VM_ISO_URL='{0}'" -f (Escape-BashSingleQuoted $VM_ISO_URL)))
[void]$sb.AppendLine(("VM_HYPERV_SWITCH='{0}'" -f (Escape-BashSingleQuoted $VM_HYPERV_SWITCH)))
if (-not [string]::IsNullOrWhiteSpace($locExtra)) {
    [void]$sb.AppendLine(("LOCATION_URL='{0}'" -f (Escape-BashSingleQuoted $locExtra.Trim())))
}

$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($Out, $sb.ToString(), $utf8NoBom)

Write-Host ""
Write-Host "Wrote $Out"
Write-Host "Next: host\create-vm-windows.ps1 (or your platform script)"
